### ISSUE TITLE
TypeError: can't compare offset-naive and offset-aware datetimes in ExecuteRequestBody.last_item

### ISSUE THREAD

**Issue by okoliechykwuka** [chain-ml/theoriq-agent-sdk#38]
When using the Theoriq library, I encounter a TypeError when comparing datetimes in the `last_item` property of `ExecuteRequestBody`. The error occurs because the library attempts to compare datetime objects where some have timezone information (offset-aware) and others don't (offset-naive).

### Stack Trace

```
TypeError: can't compare offset-naive and offset-aware datetimes
return max(self.dialog.items, key=lambda obj: obj.timestamp)
File "/usr/local/lib/python3.11/site-packages/theoriq/schemas/request.py", line 148, in last_item
if not req.last_item or not req.last_item.blocks:
File "/app/server.py", line 172, in execute
```

```
2024-11-09 10:12:14,106 - 130826122771328 - client.py-client:1038 - INFO: HTTP Request: GET https://theoriq-backend.prod-02.chainml.net/api/v1alpha1/auth/biscuits/public-key "HTTP/1.1 200 OK"
Nov 9 11:12:14 AMTypeError: can't compare offset-naive and offset-aware datetimes
Nov 9 11:12:14 AM ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 9 11:12:14 AM return max(self.dialog.items, key=lambda obj: obj.timestamp)
Nov 9 11:12:14 AM File "/usr/local/lib/python3.11/site-packages/theoriq/schemas/request.py", line 148, in last_item
Nov 9 11:12:14 AM ^^^^^^^^^^^^^
Nov 9 11:12:14 AM if not req.last_item or not req.last_item.blocks:
Nov 9 11:12:14 AM File "/app/server.py", line 172, in execute
Nov 9 11:12:14 AMTraceback (most recent call last):
Nov 9 11:12:14 AM2024-11-09 10:12:14,051 - ERROR - Error processing request: can't compare offset-naive and offset-aware datetimes
Nov 9 11:12:14 AMTypeError: can't compare offset-naive and offset-aware datetimes
Nov 9 11:12:14 AM ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 9 11:12:14 AM return max(self.dialog.items, key=lambda obj: obj.timestamp)
Nov 9 11:12:14 AM File "/usr/local/lib/python3.11/site-packages/theoriq/schemas/request.py", line 148, in last_item
Nov 9 11:12:14 AM ^^^^^^^^^^^^^
Nov 9 11:12:14 AM if not req.last_item or not req.last_item.blocks:
Nov 9 11:12:14 AM File "/app/server.py", line 172, in execute
Nov 9 11:12:14 AMTraceback (most recent call last):
Nov 9 11:12:14 AM2024-11-09 10:12:14,051 - 130826122771328 - server.py-server:199 - ERROR: Error processing request: can't compare offset-naiv
```

**Comment by aflament** [comment]
tyvm @okoliechykwuka for reporting the issue.

**Comment by aflament** [comment]
@okoliechykwuka a fix has been merged. Thank you again for reporting this issue.

**Comment by okoliechykwuka** [comment]
You are welcome @aflament
